version: '3'
services:
  web:
    image: 068cuttip/es-node-engine:v0.2
    ports:
      - "3200:3200"
    links:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    ports:
      - "9201:9200"